import {
  Film,
  LayoutDashboard,
  KanbanSquare,
  FolderOpen,
  Youtube,
  ShoppingBag,
  Home,
  Music,
  MessageSquare,
  FileText,
  UtensilsCrossed,
  Instagram,
  Gamepad2,
  BookOpen,
  Briefcase,
  Dumbbell,
  Palette,
  Calendar,
  GraduationCap,
  Cloud,
  CreditCard,
  type LucideIcon,
} from "lucide-react";

export const PROJECT_TEMPLATES: Array<{
  emoji: LucideIcon;
  title: string;
  prompt: string;
}> = [
  {
    emoji: Film,
    title: "Build a Netflix clone",
    prompt:
      "Build a complete Netflix-style streaming platform homepage with a large hero banner section, multiple horizontal scrolling movie rows organized by categories (Trending Now, Top Rated, Action Movies, etc.), and a navigation header. Use dark mode (#141414 background) with gradient overlays on the hero banner. All movie thumbnails and hero images must use real Unsplash images with the format: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=1200&q=80 - search for cinematic, movie poster, or film-related images. Each movie card should show title, rating, and year. Include hover effects that scale cards and show additional info. Create a modal component that opens when clicking a movie card, displaying full details, cast, description, and a play button. Use React state to manage modal visibility, selected movie, and row data. Break into multiple components: Navbar.tsx, HeroBanner.tsx, MovieRow.tsx, MovieCard.tsx, MovieModal.tsx. Include at least 5 categories with 8-10 movies each using mock data.",
  },
  {
    emoji: LayoutDashboard,
    title: "Build an admin dashboard",
    prompt:
      "Create a complete admin dashboard with a collapsible sidebar navigation (Dashboard, Analytics, Users, Products, Settings), top header with search bar and user profile, stat cards showing KPIs (Total Revenue, Active Users, Orders, Conversion Rate), multiple chart sections using recharts (line chart for revenue trends, bar chart for monthly sales, pie chart for traffic sources), and a data table with user/order data including sorting, filtering, pagination, and row actions (view, edit, delete). Use a clean professional layout with proper spacing and Shadcn UI components. Include a subtle background image from Unsplash for the header section: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=1200&q=80. Use React state for sidebar collapse, filter values, pagination, and modal states. Create separate components: Sidebar.tsx, Header.tsx, StatCard.tsx, RevenueChart.tsx, SalesChart.tsx, TrafficChart.tsx, DataTable.tsx. Include mock data for at least 50 users/orders.",
  },
  {
    emoji: KanbanSquare,
    title: "Build a kanban board",
    prompt:
      "Build a full-featured kanban board with drag-and-drop functionality using native HTML5 drag and drop API (onDragStart, onDragOver, onDrop, onDragEnd). Create 4 columns: Backlog, To Do, In Progress, and Done. Each task card should display title, description, assigned user avatar (use Unsplash profile images), priority badge (High/Medium/Low with color coding), and due date. Include a top navbar with board title, add task button, and filter options. Implement add task modal with form inputs (title, description, assignee, priority, due date), edit task functionality (click card to edit), delete task option, and search/filter tasks by assignee or priority. Use React state to manage tasks array, drag state, modal visibility, and filters. Create separate components: Board.tsx, Column.tsx, TaskCard.tsx, AddTaskModal.tsx, EditTaskModal.tsx. Include mock data with at least 15-20 tasks distributed across columns with realistic titles and descriptions.",
  },
  {
    emoji: FolderOpen,
    title: "Build a file manager",
    prompt:
      "Build a complete macOS-style file manager with a left sidebar showing folder tree navigation (Documents, Downloads, Photos, Videos, Music, Recent), main content area displaying files/folders in grid or list view with toggle, top toolbar with breadcrumb navigation, search bar, view options, and action buttons (upload, new folder, delete). Each file item should show thumbnail (use real Unsplash images for image files with format: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=400&q=80, use file type icons from lucide-react for others), file name, size, and modified date. Implement right-click context menu with options (Open, Rename, Delete, Move, Copy, Share), file preview modal for images and documents, rename functionality with inline editing, delete confirmation dialog, and folder creation. Use React state for current folder path, selected files, view mode (grid/list), context menu position, and modal states. Create components: Sidebar.tsx, Toolbar.tsx, FileGrid.tsx, FileList.tsx, FileItem.tsx, ContextMenu.tsx, PreviewModal.tsx, RenameDialog.tsx. Include realistic mock file/folder data with proper hierarchical structure (at least 30-40 files across multiple folders).",
  },
  {
    emoji: Youtube,
    title: "Build a YouTube clone",
    prompt:
      "Build a complete YouTube-style video platform with a collapsible left sidebar showing categories (Home, Trending, Subscriptions, Library, History), top header with logo, search bar, and user icons, main content area with video grid showing thumbnails, video player modal/page, and related videos sidebar. Each video card must display thumbnail (use real Unsplash images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=1200&q=80), title, channel name with avatar, views count, upload date, and duration badge. Implement video player modal that opens when clicking a video, showing large player area, title, channel info with subscribe button, like/dislike buttons, description section, and comments list. Include category filters at the top. Use React state for sidebar visibility, selected video, filter category, search query, and modal state. Create components: Navbar.tsx, Sidebar.tsx, VideoGrid.tsx, VideoCard.tsx, VideoPlayer.tsx, CommentSection.tsx, RelatedVideos.tsx. Include mock data with at least 30-40 videos across different categories with realistic titles, descriptions, and metadata.",
  },
  {
    emoji: ShoppingBag,
    title: "Build a store page",
    prompt:
      "Build a complete e-commerce store with a navigation header (logo, search bar, cart icon with badge, user menu), left sidebar with category filters (Electronics, Fashion, Home, Sports, etc.), price range slider, rating filter, and brand checkboxes. Main content area should display products in responsive grid with product cards showing image (use real Unsplash product images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=800&q=80), title, price, rating stars, and quick add to cart button. Include sorting dropdown (Price: Low to High, High to Low, Rating, Newest). Implement product detail modal showing large image, image gallery thumbnails, full description, size/color options, quantity selector, add to cart button, and reviews section. Create a functional shopping cart sidebar that slides in showing cart items with thumbnail, name, quantity controls (+/-), price, remove button, subtotal, and checkout button. Use React state for cart items, filters, selected product, modal visibility, and quantity. Create components: Header.tsx, Sidebar.tsx, ProductGrid.tsx, ProductCard.tsx, ProductModal.tsx, CartDrawer.tsx, CartItem.tsx, FilterSection.tsx. Include realistic mock data with at least 40-50 products across categories with prices, ratings, descriptions, and multiple images.",
  },
  {
    emoji: Home,
    title: "Build an Airbnb clone",
    prompt:
      "Build a complete Airbnb-style vacation rental platform with a top navigation bar (logo, search bar with location/dates/guests inputs, become a host link, user menu), filter chips row (Beachfront, Cabins, Trending, Pools, Countryside, etc.), and main content showing property cards in responsive grid. Each property card must show high-quality property image (use real Unsplash property/architecture images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=800&q=80), location, rating with review count, property type, dates available, and price per night with total price. Include heart icon to favorite properties. Implement property detail modal showing image carousel, full property name, host info with avatar, description, amenities list with icons (WiFi, Kitchen, Pool, etc.), bedroom/bathroom count, location map placeholder, reviews section with ratings breakdown, and booking panel with date picker, guest selector, and reserve button. Use React state for search filters, favorites, selected property, modal state, booking dates, and guest count. Create components: Navbar.tsx, SearchBar.tsx, FilterChips.tsx, PropertyGrid.tsx, PropertyCard.tsx, PropertyModal.tsx, ImageCarousel.tsx, BookingPanel.tsx, ReviewSection.tsx. Include mock data with at least 30-40 properties across different locations with detailed descriptions, amenities, and reviews.",
  },
  {
    emoji: Music,
    title: "Build a Spotify clone",
    prompt:
      "Build a complete Spotify-style music streaming app with a left sidebar showing navigation (Home, Search, Your Library) and playlists list, main content area displaying featured playlists, recently played, and album/playlist grids, and a fixed bottom playback control bar. Use dark mode (#121212 background, #1db954 for primary green). All album/playlist artwork must use real Unsplash music-related images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=600&q=80. Main content should have sections for Featured Playlists, Recently Played, Popular Albums, and Made For You. Each card shows cover art, title, and description/artist. Implement a playlist detail view that shows large cover art, title, creator, total duration, play button, and song list table with columns (#, Title, Artist, Album, Duration) and play icon on hover. Bottom player should display current song info with artwork, title, artist, playback controls (shuffle, previous, play/pause, next, repeat), progress bar with time stamps, and volume control with slider. Use React state for current track, playing state, current time, volume, selected playlist, and queue. Create components: Sidebar.tsx, MainContent.tsx, PlaylistCard.tsx, PlaylistView.tsx, TrackTable.tsx, TrackRow.tsx, Player.tsx, PlayerControls.tsx, VolumeControl.tsx. Include mock data with at least 10-15 playlists and 100+ songs with realistic titles, artists, albums, and durations.",
  },
  {
    emoji: MessageSquare,
    title: "Build a chat app",
    prompt:
      "Build a complete messaging application with a left sidebar showing conversation list (each with avatar, name, last message preview, timestamp, unread badge), top header with app name and user profile, main chat area displaying messages with sender avatars, message bubbles (different colors for sent/received), timestamps, read receipts, and message grouping by sender. Include bottom message input area with emoji picker button, attachment button, text input, and send button. Implement conversation search, create new chat modal with user selection, message actions menu (reply, copy, delete) on hover/right-click, typing indicator, and online status indicators. All user avatars must use real Unsplash profile images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=200&q=80. Use React state for conversations array, selected conversation, messages, typing users, input value, and modal states. Create components: Sidebar.tsx, ConversationList.tsx, ConversationItem.tsx, ChatHeader.tsx, MessageList.tsx, Message.tsx, MessageInput.tsx, EmojiPicker.tsx, NewChatModal.tsx. Include mock data with at least 10-15 conversations and realistic message history (50+ messages) with different message types (text, images, links) and timestamps spanning multiple days.",
  },
  {
    emoji: FileText,
    title: "Build a note-taking app",
    prompt:
      "Build a complete Apple Notes-style application with a collapsible left sidebar showing folders tree (Personal, Work, Ideas, Archive) and notes count, middle panel displaying notes list for selected folder (each showing title, preview text, and modified date), and main editor area with rich formatting toolbar. Notes list should be sortable by date, title, or manually. Editor should include formatting toolbar with buttons for: bold, italic, underline, heading levels, bullet list, numbered list, checkbox list, and code block. Include top navigation with note title (editable inline), delete button, share button, and info button showing note metadata (created date, modified date, word count). Implement search functionality across all notes, folder management (create, rename, delete), note actions (pin, archive, duplicate), and drag-and-drop notes between folders. Use a clean, minimal Unsplash image for empty state: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=1200&q=80. Use React state for folders, notes, selected note, editor content, search query, and active formatting. Create components: Sidebar.tsx, FolderTree.tsx, NotesList.tsx, NoteItem.tsx, Editor.tsx, Toolbar.tsx, TitleBar.tsx, SearchBar.tsx, EmptyState.tsx. Include mock data with at least 20-30 notes across different folders with realistic content, titles, and various formatting.",
  },
  {
    emoji: UtensilsCrossed,
    title: "Build a food delivery app",
    prompt:
      "Build a complete food delivery platform with a top navigation bar (logo, location selector with current address, search bar, cart icon with items count), category filter chips (Pizza, Burgers, Asian, Italian, Healthy, Desserts, etc.), main content showing restaurant cards in grid, and a fixed cart sidebar or bottom sheet. Each restaurant card must show appetizing food image (use real Unsplash food images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=800&q=80), restaurant name, cuisine type, rating stars with review count, delivery time, delivery fee, and offer badge if applicable. Implement restaurant detail view showing header banner image, restaurant info section, menu categories tabs, menu items grid with item name, description, price, image, and add button with quantity controls. Each menu item should have a detail modal showing large image, full description, customization options (size, add-ons, special instructions), quantity selector, and add to cart button. Cart should display items with thumbnail, name, quantity controls, price, apply coupon input, delivery fee, taxes, total amount, and checkout button. Include address selection modal and payment method selection. Use React state for cart items, selected restaurant, menu items, filters, modals, and quantities. Create components: Navbar.tsx, CategoryFilters.tsx, RestaurantGrid.tsx, RestaurantCard.tsx, RestaurantView.tsx, MenuSection.tsx, MenuItem.tsx, ItemModal.tsx, Cart.tsx, CartItem.tsx, CheckoutModal.tsx. Include mock data with at least 20-30 restaurants and 100+ menu items with realistic names, descriptions, prices, and categories.",
  },
  {
    emoji: Instagram,
    title: "Build an Instagram clone",
    prompt:
      "Build a complete Instagram-style social media feed with a top navigation bar (logo, search bar, home/messages/explore/notifications icons, user profile menu), stories bar showing circular story avatars with gradient rings, main feed with posts, and a right sidebar showing suggestions. Each post must include: user avatar and name, post timestamp, image/carousel (use real Unsplash images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=1200&q=80), like/comment/share/save action buttons, like count, caption with username and text, view all comments link, and add comment input. Stories bar should scroll horizontally with user's story first (with + icon), followed by followed users' stories. Implement story viewer modal showing full-screen story with user info, progress bars, previous/next navigation, and close button. Post detail modal should show larger image, full caption, complete comments list with replies, like animation on double-tap. Right sidebar should show user profile card and suggested users to follow. Include create post modal with image upload placeholder, caption input, location tag, and advanced settings. Use React state for posts, stories, comments, likes, saved posts, modal states, and current story. Create components: Navbar.tsx, StoriesBar.tsx, StoryCircle.tsx, StoryViewer.tsx, Feed.tsx, Post.tsx, PostActions.tsx, Comments.tsx, Sidebar.tsx, SuggestionCard.tsx, CreatePostModal.tsx, PostModal.tsx. Include mock data with at least 30-40 posts, 15-20 stories, and realistic comments, captions, and user interactions.",
  },
  {
    emoji: Gamepad2,
    title: "Build a game library",
    prompt:
      "Build a complete gaming library platform with a top navigation (logo, search bar, library/store/community tabs, user avatar), left sidebar with filters (Genre: Action, RPG, Strategy, Sports, etc., Platform: PC, PlayStation, Xbox, Nintendo Switch, Rating, Price Range), main content area with game cards in responsive grid, and sorting options (Popular, New Releases, Top Rated, Price). Each game card must show cover art (use real Unsplash gaming/tech images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=800&q=80), game title, platform icons, price/discount badge, rating stars, and favorite heart icon. Use dark mode gaming aesthetic (#0f0f0f background, #7b2cbf or #00d9ff for accents). Implement game detail modal showing large cover art, screenshot gallery, game title, developer/publisher, release date, genre tags, full description, system requirements table, user reviews section with rating breakdown, and action buttons (Add to Cart, Add to Wishlist, Play if owned). Include a favorites/library section showing owned games, wishlist tab, and recent activity. Use React state for games library, filters, favorites, cart, selected game, modal visibility, and view mode. Create components: Navbar.tsx, Sidebar.tsx, FilterSection.tsx, GameGrid.tsx, GameCard.tsx, GameModal.tsx, Screenshots.tsx, ReviewSection.tsx, SystemRequirements.tsx, CartDrawer.tsx. Include realistic mock data with at least 50+ games across genres with detailed descriptions, specs, reviews, and prices.",
  },
  {
    emoji: BookOpen,
    title: "Build a book library",
    prompt:
      "Build a complete digital book library with a clean navigation header (logo, search bar, library/discover/favorites tabs, user menu), sidebar with filters (Genre: Fiction, Non-Fiction, Mystery, Romance, Sci-Fi, etc., Author, Publication Year, Rating), main content showing books in grid with cover images, and view toggle (grid/list). Each book card must display cover image (use real Unsplash book/reading images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=600&q=80), title, author, rating stars, page count, and reading status badge (Want to Read, Currently Reading, Finished). Implement book detail modal showing large cover, title, author bio, full description, publication info, genre tags, rating breakdown with reviews, similar books section, and action buttons (Add to Reading List, Mark as Reading, Mark as Finished, Write Review). Include a personal reading list page showing currently reading books with progress bars, want to read shelf, and finished books with reading statistics (total books read, pages read, reading streak). Add reading goals widget and book recommendations based on reading history. Use React state for books data, reading lists, filters, selected book, reading progress, modal state, and review form. Create components: Navbar.tsx, Sidebar.tsx, BookGrid.tsx, BookCard.tsx, BookModal.tsx, ReviewSection.tsx, ReadingList.tsx, ProgressTracker.tsx, RecommendedBooks.tsx, ReadingGoals.tsx. Include mock data with at least 50+ books with complete details, authors, descriptions, and user reviews.",
  },
  {
    emoji: Briefcase,
    title: "Build a job board",
    prompt:
      "Build a complete job board platform with a navigation header (logo, job search bar with location input, post job button, sign in/register), left sidebar with filters (Job Type: Full-time, Part-time, Contract, Remote, Internship, Experience Level, Salary Range, Company Size, Industry), main content showing job listings, and sorting dropdown (Most Recent, Most Relevant, Highest Salary). Each job card should display company logo placeholder or icon, job title, company name, location with remote badge if applicable, salary range, posted date, job type badges, and save job icon. Use professional colors and spacing. Implement job detail modal/page showing company banner image (use professional Unsplash office images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=1200&q=80), job title, company info with logo and follow button, full job description with formatted sections (Responsibilities, Requirements, Benefits), skills tags, application deadline, share job button, and prominent apply button. Include a saved jobs page, application tracking section showing applied jobs with status (Applied, Under Review, Interview, Rejected, Accepted), company profile pages with company info, culture photos, and all open positions. Add application modal with form (resume upload placeholder, cover letter textarea, additional info). Use React state for jobs data, filters, saved jobs, applications, selected job, modal states, and application form. Create components: Navbar.tsx, SearchBar.tsx, Sidebar.tsx, FilterSection.tsx, JobList.tsx, JobCard.tsx, JobDetail.tsx, ApplyModal.tsx, SavedJobs.tsx, ApplicationStatus.tsx, CompanyProfile.tsx. Include realistic mock data with at least 10-20 job listings with complete descriptions, requirements, benefits, and company details.",
  },
  {
    emoji: Dumbbell,
    title: "Build a fitness tracker",
    prompt:
      "Build a complete fitness tracking application with a top navigation (logo, dashboard/workouts/nutrition/progress tabs, user profile), dashboard showing overview stats cards (Workouts This Week, Calories Burned, Active Minutes, Current Streak), weekly activity chart using recharts, and quick action cards (Log Workout, Log Meal, Start Workout). Include a calendar view showing workout days marked with activity icons. Each workout card must show workout type icon, exercise name, duration, calories burned, completion badge, and view details button. Use motivating Unsplash fitness images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=1200&q=80 for headers and empty states. Implement workout detail modal showing exercise list with sets/reps/weight, rest timers, completion checkboxes, notes section, and workout summary. Add workout library page categorized by type (Strength, Cardio, Yoga, HIIT, etc.) with preset workout templates. Include progress tracking page with multiple charts using recharts (weight progress line chart, body measurements, workout frequency bar chart, personal records), progress photos gallery, and goals section with progress bars. Add nutrition tracking with calorie counter, macro breakdown pie chart, meal logging with meal cards, and water intake tracker. Use React state for workouts, exercises, progress data, goals, nutrition logs, calendar events, modal states, and form inputs. Create components: Navbar.tsx, Dashboard.tsx, StatCard.tsx, ActivityChart.tsx, Calendar.tsx, WorkoutList.tsx, WorkoutCard.tsx, WorkoutModal.tsx, ExerciseList.tsx, ProgressCharts.tsx, GoalsSection.tsx, NutritionTracker.tsx, MealLog.tsx, WorkoutLibrary.tsx. Include realistic mock data with diverse workouts, exercises, progress history spanning months, and nutrition logs.",
  },
  {
    emoji: Palette,
    title: "Build a design portfolio",
    prompt:
      "Build a stunning design portfolio website with a hero section (large headline, subtitle, CTA button, creative background), navigation header (logo, work/about/contact links, theme toggle), featured projects section with large project cards in masonry/grid layout, about section with designer bio and skills, and footer with social links. Each project card must show high-quality project image (use real Unsplash creative/design images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=1200&q=80), project title, category tags, and year. Use modern, bold design with strong typography, ample white space, and smooth animations. Implement project detail modal showing project hero image, title, role, duration, tools used, full project description with formatted sections (Challenge, Solution, Result), image gallery with multiple project screenshots, testimonial section, and next/previous project navigation. Include filter buttons (All, Web Design, Mobile, Branding, UI/UX, Illustration) to filter projects by category. Add smooth scroll animations, hover effects with scale/overlay, and parallax effects on hero section. About section should include designer photo, detailed bio, skills list with proficiency indicators, tools/software list with icons, experience timeline, and contact form. Use React state for filtered projects, selected project, modal state, theme mode, and form data. Create components: Hero.tsx, Navbar.tsx, ProjectGrid.tsx, ProjectCard.tsx, ProjectModal.tsx, ImageGallery.tsx, FilterButtons.tsx, AboutSection.tsx, SkillsDisplay.tsx, Timeline.tsx, ContactForm.tsx, Footer.tsx. Include mock data with at least 20-25 diverse projects with detailed case studies, categories, images, and testimonials. Focus on premium aesthetic, creative layouts, and smooth UX.",
  },
  {
    emoji: Calendar,
    title: "Build a calendar app",
    prompt:
      "Build a complete Google Calendar-style application with a top header (month/year navigation with arrows, today button, view selector: month/week/day, create event button, search bar), left sidebar showing mini calendar for navigation, my calendars list with color-coded checkboxes, and upcoming events list. Main calendar area should display month view with date cells, event bars showing event titles with category colors, and ability to see multiple events per day. Implement week view with time slots (hourly from 6 AM to 10 PM), event blocks positioned by time with duration-based heights, and drag to resize events. Day view should show detailed hourly schedule with larger event blocks and more info. Each event should display title, time, location icon if applicable, and category color bar. Implement create/edit event modal with form inputs (title, date picker, start time, end time, repeat options dropdown, location, description textarea, category/calendar selector with color picker, reminder options). Include all-day events section above time grid, event detail popover on click showing full info and edit/delete buttons, and multi-day event spanning. Add agenda view showing chronological list of upcoming events. Use a subtle Unsplash productivity image for empty state: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=1200&q=80. Use React state for current date, view mode, events array, selected event, calendars with visibility toggles, modal state, and form data. Create components: Header.tsx, Sidebar.tsx, MiniCalendar.tsx, CalendarList.tsx, MonthView.tsx, WeekView.tsx, DayView.tsx, AgendaView.tsx, EventModal.tsx, EventCard.tsx, TimeGrid.tsx, DateCell.tsx. Include realistic mock data with 50+ events spanning multiple months, different categories (work, personal, family, etc.), recurring events, and all-day events.",
  },
  {
    emoji: GraduationCap,
    title: "Build a learning platform",
    prompt:
      "Build a complete online learning platform with a navigation header (logo, browse courses/my learning/dashboard tabs, search bar, notifications, user profile), hero section with featured course carousel, course categories grid, and popular courses section. Each course card must show course thumbnail (use real Unsplash education/classroom images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=800&q=80), title, instructor name with avatar, rating stars with student count, duration, lesson count, level badge (Beginner/Intermediate/Advanced), price/free tag, and enroll button. Use warm, educational colors. Implement course detail page showing course banner image, title, instructor section with bio and credentials, course description with what you'll learn bullets, curriculum accordion showing sections and lessons with video/quiz icons and durations, requirements section, student reviews with rating breakdown, related courses, and enroll CTA. Include student dashboard showing enrolled courses with progress bars and continue learning buttons, completed courses, certificates earned, and learning streak. Add course player page with left lesson sidebar (course curriculum with checkmarks for completed), main video player area with controls, lesson title and description, tabs for overview/resources/discussions, and next lesson button. Progress tracking should show overall course progress, quiz scores, and time spent. Include quiz functionality with multiple choice questions, submit button, score display, and review answers. Use React state for courses, enrolled courses, progress data, current lesson, quiz answers, modal states, and filters. Create components: Navbar.tsx, Hero.tsx, CourseGrid.tsx, CourseCard.tsx, CourseDetail.tsx, Curriculum.tsx, ReviewSection.tsx, Dashboard.tsx, CoursePlayer.tsx, LessonSidebar.tsx, VideoPlayer.tsx, QuizComponent.tsx, ProgressTracker.tsx, CertificateCard.tsx. Include mock data with 30-40 courses across categories (Development, Business, Design, Marketing, etc.), detailed curriculum with 50+ lessons per course, reviews, and student progress tracking.",
  },
  {
    emoji: Cloud,
    title: "Build a weather app",
    prompt:
      "Build a beautiful Apple Weather-style application with a search bar for cities at top, current location weather as hero section showing large temperature, weather condition with icon, feels like temp, high/low, and location name with beautiful weather background image (use real Unsplash weather/nature images: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=1200&q=80 - search for sunny, rainy, cloudy, snowy based on condition). Include horizontal scrolling hourly forecast strip showing time, weather icon, and temperature for next 24 hours. Add 7-day forecast section with daily cards showing day name, weather icon, high/low temps, and precipitation chance. Include detailed weather metrics cards showing: wind speed and direction with animated icon, humidity percentage with gauge, UV index with safety level, visibility distance, air quality index with color coding, sunrise/sunset times with sun position arc, and pressure. Implement city search with autocomplete suggestions, favorite cities list with quick-switch cards showing current temp and conditions, and location permission request. Add weather alerts banner if applicable (storm warning, heat advisory, etc.). Use dynamic gradients and icons based on weather conditions (sunny: bright blues/yellows, rainy: grays/blues, cloudy: muted, night: dark purples/blues). Use React state for current weather, hourly forecast, daily forecast, favorite cities, selected city, search query, and loading states. Create components: SearchBar.tsx, CurrentWeather.tsx, HourlyForecast.tsx, DailyForecast.tsx, DayCard.tsx, WeatherDetails.tsx, MetricCard.tsx, FavoriteCities.tsx, CityCard.tsx, WeatherAlert.tsx, SunPosition.tsx. Include realistic mock weather data for multiple cities with all metrics, forecasts, and conditions. Focus on beautiful visual design with weather-appropriate backgrounds and smooth animations.",
  },
  {
    emoji: CreditCard,
    title: "Build a banking dashboard",
    prompt:
      "Build a complete banking dashboard with a secure-looking header (bank logo, accounts/transfer/bills/settings navigation, notifications bell, user profile), accounts overview section showing account cards (checking, savings, credit cards) with account number (masked), current balance, available balance, and view details button. Use professional, trustworthy colors (navy, white, subtle accent colors). Each account card should have a finance-related Unsplash image in header: https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w=1200&q=80. Include recent transactions section with filterable table showing date, description with merchant logo/icon, category tag, amount (color-coded for income/expense), and status badge. Add spending analytics section with charts using recharts: spending by category pie chart, monthly spending trend line chart, income vs expenses bar chart, and budget progress bars with categories (Groceries, Transportation, Entertainment, etc.). Implement quick transfer form with recipient selector, account dropdown, amount input, note field, and confirm button. Include bills section showing upcoming bills with due dates, amount, auto-pay toggle, and pay now button. Add detailed transaction view modal showing full transaction info, merchant details, category, notes, and categorize options. Use React state for accounts, transactions, budgets, transfers, selected account, modal states, filter options, and form data. Create components: Header.tsx, AccountCard.tsx, TransactionTable.tsx, TransactionRow.tsx, SpendingCharts.tsx, TransferForm.tsx, BillsList.tsx, BillCard.tsx, TransactionModal.tsx, BudgetSection.tsx. Include realistic mock financial data with 50+ transactions, multiple accounts, bills, and spending categories.",
  },
];
